server:
  port: 8090

spring:
  application:
    name: auth-service
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:flowforge;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DATABASE_USER:sa}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: ${DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: ${DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}

security:
  jwt:
    secret: ${JWT_SECRET:changeme-super-secret-key-for-jwt-signing}
    expiration: 86400000 # 24 hours

