spring:
  application:
    name: workflow-service
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:flowforge;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${POSTGRES_USER:sa}
    password: ${POSTGRES_PASSWORD:}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: -1
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: ${DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: ${DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
  sql:
    init:
      mode: never
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8082

logging:
  level:
    com.flowforge: DEBUG
    org.springframework.web: INFO

